<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MdViewer.Core\MdViewer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3485.44" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>md-viewer</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Version>1.3.0</Version>
    <Authors>hoopdad</Authors>
    <Description>A fast, secure, read-only Markdown viewer for Windows.</Description>
  </PropertyGroup>

</Project>
